export const GET_ERRORS = "GET_ERRORS";
export const TEACHER_LOADING = "TEACHER_LOADING";
export const SET_CURRENT_TEACHER = "SET_CURRENT_TEACHER";
export const CHANGE_PROFILE_IMAGE = "CHANGE_PROFILE_IMAGE";
export const POST_ASSIGNMENT = "POST_ASSIGNMENT";
export const STUDENT_REGISTRATION = "STUDENT_REGISTRATION";
